title: mcdavid henderson work
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.25
  brandStrength: 0.9375
  rhythmicContrast: 0.25
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  lightness: 0.625
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: mcdavidhenderson
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.6589940276462585
layout_spectrum: 0.8984962
